# This is a basic workflow to help you get started with Actions

name: Generate PDF

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello_world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate Model Code PDF
        id: model-code
        uses: Zygar/pagedjs-cli-github-action@main
        with:
          target_url: https://policy.cookalliance.org/model-code/
      - name: Generate Model Legislation PDF
        id: model-legislation
        uses: Zygar/pagedjs-cli-github-action@main
        with:
          target_url: https://policy.cookalliance.org/model-legislation/
      - name: Generate Model Legislation PDF
        id: introduction
        uses: Zygar/pagedjs-cli-github-action@main
        with:
          target_url: https://policy.cookalliance.org/introduction/
