# This is a basic workflow to help you get started with Actions

name: Generate PDF

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello_world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate Model Code PDF
        id: model-code
        uses: Zygar/pagedjs-cli-github-action@main
        with:
          target_url: https://policy.cookalliance.org/model-code/
          additional_script: ./marginNotesBuild.js
      - name: Save Model Code PDF
        id: model-code-save
        uses: actions/upload-artifact@v2
        with:
          name: model-code.pdf
          path: ${{ github.workspace }}/output.pdf
      - name: Copy Model Code to folder
        run: cp -f ${{ github.workspace }}/output.pdf ${{ github.workspace }}/static/model-code.pdf
      - name: Generate Model Legislation PDF
        id: model-legislation
        uses: Zygar/pagedjs-cli-github-action@main
        with:
          target_url: https://policy.cookalliance.org/model-legislation/
          additional_script: ./marginNotesBuild.js
      - name: Save Model Legislation PDF
        id: model-legislation-save
        uses: actions/upload-artifact@v2
        with:
          name: model-legislation.pdf
          path: ${{ github.workspace }}/output.pdf
      - name: Copy Model Leg to folder
        run: cp -f ${{ github.workspace }}/output.pdf ${{ github.workspace }}/static/model-legislation.pdf
      - name: Introduction
        id: introduction
        uses: Zygar/pagedjs-cli-github-action@main
        with:
          target_url: https://policy.cookalliance.org/introduction/
          additional_script: ./marginNotesBuild.js
      - name: Save Introduction PDF
        id: introduction-save
        uses: actions/upload-artifact@v2
        with:
          name: introduction.pdf
          path: ${{ github.workspace }}/output.pdf
      - name: Copy Introduction to folder
        run: cp -f ${{ github.workspace }}/output.pdf ${{ github.workspace }}/static/introduction.pdf
      - name: Commit changes to working tree
        uses: EndBug/add-and-commit@v7 
        with:
          author_name: Publisher
          author_email: hello@andyayrey.com
          default_author: github_actor
          message: 'Updates generated PDFs'
          pathspec_error_handling: ignore
          pull: 'NO-PULL'
          push: true